name: Build & Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install npm dependencies & build

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to branch for github pages

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
